version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/codedeploy-tutorial
hooks:
  AfterInstall:
    - location: scripts/after_install.sh
      runas: ec2-user

  ApplicationStart:
    - location: scripts/application_start.sh
      runas: ec2-user
