version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/codedeploy-tutorial

file_exists_behavior: OVERWRITE

permissions:
  - object: /
    pattern: "**"
    owner: ec2-user
    group: ec2-user

  - object: /scripts
    pattern: "**"
    owner: ec2-user
    group: ec2-user
    mode: 744

hooks:
  ApplicationStart:
    - location: scripts/application_start.sh
      runas: ec2-user
