version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/codedeploy-tutorial

permissions:
  - object: /
    pattern: "**"
    owner: ec2-user
    group: ec2-user

  - object: /scripts
    pattern: "**"
    owner: ec2-user
    group: ec2-user
    mode: 744

hooks:
  AfterInstall:
    - location: scripts/after_install.sh
      runas: ec2-user

  ApplicationStart:
    - location: scripts/application_start.sh
      runas: ec2-user
