name: deploy-to-ec2
on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  create-codedeploy-deployment:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1-node16
        with:
          role-to-assume: ${{ secrets.IAM_ROLE_GITHUB }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: |
          npm run build

      - name: Deploy build to s3
        run: |
          aws deploy push \
          --application-name ${{ secrets.CODEDEPLOY_APPLICATION_NAME }} \
          --s3-location s3://${{ secrets.REVISION_BUCKET }}/${{ secrets.CODEDEPLOY_APPLICATION_NAME }}.zip \
          --source .

      - name: Create Codedeploy Deployment
        id: deploy
        run: |
          aws deploy create-deployment \
          --application-name ${{ secrets.CODEDEPLOY_APPLICATION_NAME }} \
          --deployment-group-name ${{ secrets.CODEDEPLOY_DEPLOYMENT_GROUP_NAME }} \
          --deployment-config-name CodeDeployDefault.OneAtATime \
          --s3-location bucket=${{ secrets.REVISION_BUCKET }},key=${{ secrets.CODEDEPLOY_APPLICATION_NAME }}.zip,bundleType=zip\
